/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * PASS2RENT widgets
 * For partner reservation website
 * OpenAPI spec version: v0.0.1
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  BillClient,
  BillClientDetail,
  CountryEntry,
  VehicleCategoryBookingPublic,
} from "../../model/generated";

export const validateVatNumber = <TData = AxiosResponse<BillClientDetail>>(
  billClient: BillClient,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `/api/booking/valildate-client-data`,
    billClient,
    options,
  );
};
export const getBookableCategories = <
  TData = AxiosResponse<VehicleCategoryBookingPublic[]>,
>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/booking/vehicle-categories`, options);
};
export const getAvailableCountries = <TData = AxiosResponse<CountryEntry[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/booking/available-countries`, options);
};
export type ValidateVatNumberResult = AxiosResponse<BillClientDetail>;
export type GetBookableCategoriesResult = AxiosResponse<
  VehicleCategoryBookingPublic[]
>;
export type GetAvailableCountriesResult = AxiosResponse<CountryEntry[]>;
